name: CI/CD

# workflow triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npm run test
      - name: Execute build
        run: npm run build
        env:
          VITE_APP_PUBLIC_URL: /example-react-cicd/
